[keys]
  personal = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHGminsJAXUJkc7TH7qHU6RNdZuMcWIwdx+zZCDpDiUG"
  work = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPdfrqOCDx1cjTn3ZFITw82y2ujZMFFaS9qowOeQEzpd"
  emu = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEi0B051rYqFXUEhqbH9PfLEnB5yY5m0GqcmpWhfW5wm"
